
vscode:
  extensions:
    - DEVSENSE.composer-php-vscode
    - vivaxy.vscode-conventional-commits
    - ms-azuretools.vscode-docker
    - eamodio.gitlens

    - bmewburn.vscode-intelephense-client

    - mblode.twig-language

tasks:
  - name: Composer Install
    init: cd app && composer install
  - name: NPM Install
    init: cd app && npm install --dev
    command: cd app && npm run watch
  - name: Database
    init: cd app && docker-compose up -d && sleep 10 && bin/console doctrine:migrations:migrate -n && docker-compose stop
    command: docker-compose up
    env:
      DATABASE_URL: mysql://berichtsheft:berichtsheft@127.0.0.1:3306/berichtsheft

ports:
  - name: Website
    port: 80
    onOpen: ignore
  - name: Database
    port: 3306
    onOpen: ignore


