
vscode:
  extensions:
    - DEVSENSE.composer-php-vscode
    - vivaxy.vscode-conventional-commits
    - ms-azuretools.vscode-docker
    - eamodio.gitlens

tasks:
  - name: Composer Install
    init: cd app && composer install --dev
  - name: Database
    init: cd app && docker-compose up -d && sleep 10 && bin/console doctrine:migrations:migrate && docker-compose down
    command: docker-compose up
    env:
      DATABASE_URL: mysql://berichtsheft:berichtsheft@127.0.0.1:3306/berichtsheft

ports:
  - name: Website
    port: 80
