version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.22.0/24


services:
  web:
    image: nginx:1.23.1
    ports:
    - "80:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        ipv4_address: 10.1.22.30
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      DATABASE_URL: 'mysql://berichtsheft:berichtsheft@mysql:3306/berichtsheft?serverVersion=mariadb-10.9.3&charset=utf8mb4'
    networks:
      default:
        ipv4_address: 10.1.22.20
  mysql:
    image: mariadb:10.9.3
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'berichtsheft'
      MYSQL_PASSWORD: 'berichtsheft'
      MYSQL_DATABASE: 'berichtsheft'
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 10.1.22.10

volumes:
  mysqldata: {}