version: '3'

services:
  web:
    image: nginx:1.23.1
    ports:
    - "80:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      DATABASE_URL: 'mysql://berichtsheft:berichtsheft@mysql:3306/berichtsheft?serverVersion=mariadb-10.9.3&charset=utf8mb4'
  mysql:
    image: mariadb:10.9.3
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'berichtsheft'
      MYSQL_PASSWORD: 'berichtsheft'
      MYSQL_DATABASE: 'berichtsheft'
    ports:
      - "3306:3306"

volumes:
  mysqldata: {}